# Generated by Django 4.2.7 on 2023-11-29 15:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlaceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Название"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Короткое описание"),
                ),
                (
                    "long_description",
                    tinymce.models.HTMLField(
                        blank=True, verbose_name="Полное описание"
                    ),
                ),
                ("longitude", models.FloatField(verbose_name="Долгота точки")),
                ("latitude", models.FloatField(verbose_name="Широта точки")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.placecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.CreateModel(
            name="PlaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        verbose_name="Порядковый номер:",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(upload_to="img", verbose_name="Картинка"),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="core.placename",
                        verbose_name="Место",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка",
                "verbose_name_plural": "Картинки",
                "ordering": ["sequence_number"],
            },
        ),
    ]
