# Generated by Django 4.2.7 on 2023-12-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_places",
                to="core.placename",
                verbose_name="Место, к которому написано",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="published_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время публикации"
            ),
        ),
    ]
