# Generated by Django 4.2.7 on 2023-12-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeimage",
            name="picture",
            field=models.FileField(upload_to="media_files/", verbose_name="Медиафайлы"),
        ),
    ]
