# Generated by Django 4.2.7 on 2023-12-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_comment_options_alter_comment_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placename",
            name="published_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время публикации"
            ),
        ),
        migrations.AlterField(
            model_name="placename",
            name="title",
            field=models.CharField(max_length=128, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="placename",
            name="update_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время изменения публикации"
            ),
        ),
    ]
