# Generated by Django 4.2.7 on 2023-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_placeimage_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeimage",
            name="is_video",
            field=models.BooleanField(default=False),
        ),
    ]
