# Generated by Django 4.2.7 on 2023-12-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_comment_status_alter_comment_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="update_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время изменения комментария"
            ),
        ),
    ]
