# Generated by Django 4.2.7 on 2023-12-05 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_alter_comment_update_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceLikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.BooleanField(default=False, verbose_name="Like")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата и время"
                    ),
                ),
                (
                    "liked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Поставил лайк",
                    ),
                ),
                (
                    "place_post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.placename",
                        verbose_name="Пост места",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place like",
                "verbose_name_plural": "Place likes",
            },
        ),
    ]
